<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.12 on linux)" generated="20231124 14:45:00.169" rpa="false" schemaversion="3">
<suite id="s1" name="Add Reference" source="/home/hennisep/ohtu-miniprojekti/src/tests/add_reference.robot">
<test id="s1-t1" name="User Can Start Application" line="6">
<kw name="Start Application" library="resource">
<kw name="Run Application">
<msg timestamp="20231124 14:45:00.208" level="FAIL">No keyword with name 'Run Application' found.</msg>
<status status="FAIL" starttime="20231124 14:45:00.208" endtime="20231124 14:45:00.209"/>
</kw>
<status status="FAIL" starttime="20231124 14:45:00.206" endtime="20231124 14:45:00.210"/>
</kw>
<status status="FAIL" starttime="20231124 14:45:00.205" endtime="20231124 14:45:00.212">No keyword with name 'Run Application' found.</status>
</test>
<status status="FAIL" starttime="20231124 14:45:00.173" endtime="20231124 14:45:00.213"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Add Reference">Add Reference</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231124 14:45:00.202" level="ERROR">Error in file '/home/hennisep/ohtu-miniprojekti/src/tests/resource.robot' on line 2: Initializing library 'UILibrary' with no arguments failed: OperationalError: no such table: bibtex
Traceback (most recent call last):
  File "/home/hennisep/ohtu-miniprojekti/src/UILibrary.py", line 7, in __init__
    self.ui = UI(self.io)
  File "/home/hennisep/ohtu-miniprojekti/src/UI/ui.py", line 10, in __init__
    self.app = AppLogic(BibTex_Repository(get_data_base_connection()))
  File "/home/hennisep/ohtu-miniprojekti/src/services/app_logic.py", line 4, in __init__
    self.citations = self.initialize_citations()
  File "/home/hennisep/ohtu-miniprojekti/src/services/app_logic.py", line 7, in initialize_citations
    return self.bib_repo.fetch_all()
  File "/home/hennisep/ohtu-miniprojekti/src/repositories/bibtex_repository.py", line 23, in fetch_all
    cursor.execute('''SELECT * FROM bibtex''')
sqlite3.OperationalError: no such table: bibtex</msg>
</errors>
</robot>
