<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.10.12 on linux)" generated="20231124 15:04:39.587" rpa="false" schemaversion="4">
<suite id="s1" name="Tests" source="/home/hennisep/ohtu-miniprojekti/src/tests">
<suite id="s1-s1" name="Add Reference" source="/home/hennisep/ohtu-miniprojekti/src/tests/add_reference.robot">
<test id="s1-s1-t1" name="User Can Start Application" line="6">
<kw name="Start Application" library="resource">
<kw name="Run Application">
<msg timestamp="20231124 15:04:39.613" level="FAIL">No keyword with name 'Run Application' found.</msg>
<status status="FAIL" starttime="20231124 15:04:39.613" endtime="20231124 15:04:39.613"/>
</kw>
<status status="FAIL" starttime="20231124 15:04:39.611" endtime="20231124 15:04:39.613"/>
</kw>
<status status="FAIL" starttime="20231124 15:04:39.611" endtime="20231124 15:04:39.613">No keyword with name 'Run Application' found.</status>
</test>
<test id="s1-s1-t2" name="User Can Fill Book References With Right Inputs" line="9">
<kw name="Start Application" library="resource">
<kw name="Run Application">
<msg timestamp="20231124 15:04:39.615" level="FAIL">No keyword with name 'Run Application' found.</msg>
<status status="FAIL" starttime="20231124 15:04:39.615" endtime="20231124 15:04:39.615"/>
</kw>
<status status="FAIL" starttime="20231124 15:04:39.613" endtime="20231124 15:04:39.615"/>
</kw>
<status status="FAIL" starttime="20231124 15:04:39.613" endtime="20231124 15:04:39.615">No keyword with name 'Run Application' found.</status>
</test>
<status status="FAIL" starttime="20231124 15:04:39.602" endtime="20231124 15:04:39.615"/>
</suite>
<suite id="s1-s2" name="Database" source="/home/hennisep/ohtu-miniprojekti/src/tests/database.robot">
<test id="s1-s2-t1" name="User Can Save References To Database Succesfully" line="5">
<status status="FAIL" starttime="20231124 15:04:39.617" endtime="20231124 15:04:39.618">Test cannot be empty.</status>
</test>
<test id="s1-s2-t2" name="User Can Save References To Database Unsuccesfully" line="8">
<status status="FAIL" starttime="20231124 15:04:39.618" endtime="20231124 15:04:39.618">Test cannot be empty.</status>
</test>
<status status="FAIL" starttime="20231124 15:04:39.616" endtime="20231124 15:04:39.618"/>
</suite>
<status status="FAIL" starttime="20231124 15:04:39.588" endtime="20231124 15:04:39.619"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="4" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="4" skip="0" id="s1" name="Tests">Tests</stat>
<stat pass="0" fail="2" skip="0" id="s1-s1" name="Add Reference">Tests.Add Reference</stat>
<stat pass="0" fail="2" skip="0" id="s1-s2" name="Database">Tests.Database</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231124 15:04:39.611" level="ERROR">Error in file '/home/hennisep/ohtu-miniprojekti/src/tests/resource.robot' on line 2: Initializing library 'UILibrary' with no arguments failed: OperationalError: no such table: bibtex
Traceback (most recent call last):
  File "/home/hennisep/ohtu-miniprojekti/src/UILibrary.py", line 7, in __init__
    self.ui = UI(self.io)
  File "/home/hennisep/ohtu-miniprojekti/src/UI/ui.py", line 10, in __init__
    self.app = AppLogic(BibTex_Repository(get_data_base_connection()))
  File "/home/hennisep/ohtu-miniprojekti/src/services/app_logic.py", line 4, in __init__
    self.citations = self.initialize_citations()
  File "/home/hennisep/ohtu-miniprojekti/src/services/app_logic.py", line 7, in initialize_citations
    return self.bib_repo.fetch_all()
  File "/home/hennisep/ohtu-miniprojekti/src/repositories/bibtex_repository.py", line 23, in fetch_all
    cursor.execute('''SELECT * FROM bibtex''')
sqlite3.OperationalError: no such table: bibtex</msg>
<msg timestamp="20231124 15:04:39.617" level="ERROR">Error in file '/home/hennisep/ohtu-miniprojekti/src/tests/resource.robot' on line 2: Initializing library 'UILibrary' with no arguments failed: OperationalError: no such table: bibtex
Traceback (most recent call last):
  File "/home/hennisep/ohtu-miniprojekti/src/UILibrary.py", line 7, in __init__
    self.ui = UI(self.io)
  File "/home/hennisep/ohtu-miniprojekti/src/UI/ui.py", line 10, in __init__
    self.app = AppLogic(BibTex_Repository(get_data_base_connection()))
  File "/home/hennisep/ohtu-miniprojekti/src/services/app_logic.py", line 4, in __init__
    self.citations = self.initialize_citations()
  File "/home/hennisep/ohtu-miniprojekti/src/services/app_logic.py", line 7, in initialize_citations
    return self.bib_repo.fetch_all()
  File "/home/hennisep/ohtu-miniprojekti/src/repositories/bibtex_repository.py", line 23, in fetch_all
    cursor.execute('''SELECT * FROM bibtex''')
sqlite3.OperationalError: no such table: bibtex</msg>
</errors>
</robot>
