<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.10.12 on linux)" generated="20231124 14:45:00.732" rpa="false" schemaversion="4">
<suite id="s1" name="Ohtu-Miniprojekti" source="/home/hennisep/ohtu-miniprojekti">
<suite id="s1-s1" name="Src" source="/home/hennisep/ohtu-miniprojekti/src">
<suite id="s1-s1-s1" name="Tests" source="/home/hennisep/ohtu-miniprojekti/src/tests">
<suite id="s1-s1-s1-s1" name="Add Reference" source="/home/hennisep/ohtu-miniprojekti/src/tests/add_reference.robot">
<test id="s1-s1-s1-s1-t1" name="User Can Start Application" line="6">
<kw name="Start Application" library="resource">
<kw name="Run Application">
<msg timestamp="20231124 14:45:00.865" level="FAIL">No keyword with name 'Run Application' found.</msg>
<status status="FAIL" starttime="20231124 14:45:00.860" endtime="20231124 14:45:00.866"/>
</kw>
<status status="FAIL" starttime="20231124 14:45:00.855" endtime="20231124 14:45:00.870"/>
</kw>
<status status="FAIL" starttime="20231124 14:45:00.853" endtime="20231124 14:45:00.871">No keyword with name 'Run Application' found.</status>
</test>
<status status="FAIL" starttime="20231124 14:45:00.818" endtime="20231124 14:45:00.873"/>
</suite>
<status status="FAIL" starttime="20231124 14:45:00.813" endtime="20231124 14:45:00.875"/>
</suite>
<status status="FAIL" starttime="20231124 14:45:00.806" endtime="20231124 14:45:00.877"/>
</suite>
<status status="FAIL" starttime="20231124 14:45:00.748" endtime="20231124 14:45:00.879"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Ohtu-Miniprojekti">Ohtu-Miniprojekti</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Src">Ohtu-Miniprojekti.Src</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1" name="Tests">Ohtu-Miniprojekti.Src.Tests</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1-s1" name="Add Reference">Ohtu-Miniprojekti.Src.Tests.Add Reference</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231124 14:45:00.848" level="ERROR">Error in file '/home/hennisep/ohtu-miniprojekti/src/tests/resource.robot' on line 2: Initializing library 'UILibrary' with no arguments failed: OperationalError: no such table: bibtex
Traceback (most recent call last):
  File "/home/hennisep/ohtu-miniprojekti/src/UILibrary.py", line 7, in __init__
    self.ui = UI(self.io)
  File "/home/hennisep/ohtu-miniprojekti/src/UI/ui.py", line 10, in __init__
    self.app = AppLogic(BibTex_Repository(get_data_base_connection()))
  File "/home/hennisep/ohtu-miniprojekti/src/services/app_logic.py", line 4, in __init__
    self.citations = self.initialize_citations()
  File "/home/hennisep/ohtu-miniprojekti/src/services/app_logic.py", line 7, in initialize_citations
    return self.bib_repo.fetch_all()
  File "/home/hennisep/ohtu-miniprojekti/src/repositories/bibtex_repository.py", line 23, in fetch_all
    cursor.execute('''SELECT * FROM bibtex''')
sqlite3.OperationalError: no such table: bibtex</msg>
</errors>
</robot>
